version: '2'
services:
  mysql:
    image: mysql
    ports: ["8888:3306"]
    hostname: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=Users
  web:
    build: pictolearn-docker
    image: pictolearn-web
    #ports: ["5555:8080"]
    hostname: web
    tty: true
    volumes:
      - /Users/AGanesan/docker/docker-tutorial/resources/docker-compose-spring-boot/logs:/usr/local/pictolearn/logs
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DB_PORT=tcp://mysql:3306  
  
  dispatcher:
    build: pictolearn-dispatcher
    image: pictolearn-dispatcher
    ports: ["1111:8080"]
    depends_on:
      - web